export enum ExceptionType {
  ERROR = 'ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  FORBIDDEN = 'FORBIDDEN',
  UNPROCESSABLE = 'UNPROCESSABLE',
  EXTERNAL_ERROR = 'EXTERNAL_ERROR',
  PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
}
